---
title: "BST210_Project_Draft"
format: pdf
editor: visual
---

# Data & EDA

## Data

```{r}
library(sampleSelection)
library(tidyverse)   
library(haven)      
library(NHANES)     
library(dplyr)  
library(purrr)
library(lubridate)
library(mice)
library(naniar)
library(ggrepel)
```

### 13-14

```{r}
getwd()
setwd("data/13_14")

ALQ <- read_xpt("ALQ_H.XPT")
BIOPRO <- read_xpt("BIOPRO_H.XPT")
BMX <- read_xpt("BMX_H.XPT")
BPX <- read_xpt("BPX_H.XPT")
CAFE <- read_xpt("CAFE_H.XPT")
CUSEZN <- read_xpt("CUSEZN_H.XPT") #zinc
DEMO <- read_xpt("DEMO_H.XPT")
DPQ_raw <- read_xpt("DPQ_H.XPT")
GLU <- read_xpt("GLU_H.XPT")
INQ <- read_xpt("INQ_H.XPT")
PAQ <- read_xpt("PAQ_H.XPT")
SLQ <- read_xpt("SLQ_H.XPT")
TCHOL <- read_xpt("TCHOL_H.XPT")
VID <- read_xpt("VID_H.XPT")
VITB12 <- read_xpt("VITB12_H.XPT")

DPQ <- DPQ_raw %>% 
    filter(complete.cases(select(., starts_with("DPQ"))[-1])) %>% 
    mutate(depression_score = rowSums(select(., starts_with("DPQ"))[-1])) |> #%>% 
    mutate(depression_category = case_when(
        depression_score <= 4 ~ "Minimal",
        depression_score <= 9 ~ "Mild",
        depression_score <= 14 ~ "Moderate",
        depression_score <= 19 ~ "Moderately severe",
        depression_score >= 20 ~ "Severe"
    ))

BPX <- BPX %>%
  mutate(
    MAP1 = (1 / 3) * BPXSY1 + (2 / 3) * BPXDI1,
    MAP2 = (1 / 3) * BPXSY2 + (2 / 3) * BPXDI2,
    MAP3 = (1 / 3) * BPXSY3 + (2 / 3) * BPXDI3,
    avg_MAP = rowMeans(cbind(MAP1, MAP2, MAP3), na.rm = TRUE)
  )

PAQ <- PAQ %>%
  mutate(
    PAQ710 = case_when(
      PAQ710 == 8 ~ 0,
      PAQ710 == 77 ~ NA_real_,
      PAQ710 == 99 ~ NA_real_,
      TRUE ~ as.numeric(PAQ710)
    ),
    PAQ715 = case_when(
      PAQ715 == 8 ~ 0,
      PAQ715 == 77 ~ NA_real_,
      PAQ715 == 99 ~ NA_real_,
      TRUE ~ as.numeric(PAQ715)
    ),
    screen_time = PAQ710 + PAQ715
  )



datasets <- list(ALQ, BIOPRO, BMX,BPX, DEMO , PAQ, SLQ, TCHOL, DPQ , INQ, VID, VITB12)
test <- reduce(datasets, inner_join, by = "SEQN")  


temp <- select(test, SEQN, RIDAGEYR, RIAGENDR, RIDRETH3, ALQ130 , BMXBMI, avg_MAP,INDFMMPI, screen_time ,PAD680 ,LBDTCSI, SLD010H ,SLQ050, SLQ060, depression_score, depression_category, LBXVIDMS, LBDB12SI)

dat_raw <- left_join(SLQ, temp)

# Clean Data 

## rename cols
new_colnames <- c(
  
  "ID",                           # SEQN; Respondent sequence number
  "sleep_hours",            # SLD010H; Usual hours of sleep on weekdays
  "sleep_trouble",          # SLQ050; Ever told doctor had trouble sleeping?
  "sleep_diagnosed",        # SLQ060; Ever told by doctor have sleep disorder?
  "age",                          # RIDAGEYR; Age at screening
  "gender",                       # RIAGENDR; Gender
  "race_ethnicity",               # RIDRETH3; Race/Ethnicity category
  "alcohol",     # ALQ120Q; How often drank alcohol in past 12 months
  "BMI",
  "avg_MAP",              # avg_MAP
  "income", # INDFMMPI; Family income to poverty ratio
  "screen_time",                   # TV+computer time
  "sedentary_minutes",            # PAD680; Minutes of sedentary activity
  "total_cholesterol",            # LBDTCSI; Total cholesterol (mg/dL)

  "depression_score",             # depression_score; Calculated total depression score
  "depression_category",          # depression_category; Depression score category
  "vitamin_d",                    # LBXVIDMS; Vitamin D level (nmol/L)
  "vitamin_b12"                   # LBDB12SI; Vitamin B12 level (pmol/L)
)
colnames(dat_raw) <- new_colnames
# remove all lines with NA
dat_raw[dat_raw == ""] <- NA
dat_clean_1314 <- dat_raw |>
  drop_na() |>
  filter(alcohol < 16  & sedentary_minutes < 6000 & sleep_hours < 66 & sleep_trouble < 3 & sleep_diagnosed < 3 & vitamin_b12 <= 2500 & vitamin_d <= 200, total_cholesterol < 20) |>
  mutate(across(c(ID, sleep_trouble, sleep_diagnosed, gender, race_ethnicity), as.factor))
```


### 2020

```{r}

```







